### ISSUE TITLE
misaligned icons on group chat

### ISSUE THREAD

**Issue by Tropix126** [intrnl/FluentDiscord#1]
![image](https://user-images.githubusercontent.com/42101043/52837656-3a7d1300-30b5-11e9-849b-ce408d068ed0.png)

**Comment by intrnl** [comment]
![discord_mhovzwu4vp](https://user-images.githubusercontent.com/20620901/52841048-b74bd380-312d-11e9-8d21-c2379d91cb3f.png)
dont really see how they're misaligned

**Comment by Tropix126** [comment]
yeah probably misworded that badly, they are clipping out of the grey area, it might be fixed with making the icons the same color as the member list then making them as tall as the titlebar or smth and vertically aligning them after that.

**Comment by Tropix126** [comment]
or maybe just making the members list larger which didnt look too bad when i tested it

**Comment by intrnl** [comment]
I'm closing this as it's an intended thing for now, perhaps soon enough I'll try to think up of any other solutions.
